# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\npose.proto\"\x1d\n\x0fkeyframeRequest\x12\n\n\x02id\x18\x01 \x01(\r\"#\n\x10keyframeResponse\x12\x0f\n\x07message\x18\x01 \x01(\t27\n\x04Pose\x12/\n\x08TakePose\x12\x10.keyframeRequest\x1a\x11.keyframeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_KEYFRAMEREQUEST']._serialized_start=14
  _globals['_KEYFRAMEREQUEST']._serialized_end=43
  _globals['_KEYFRAMERESPONSE']._serialized_start=45
  _globals['_KEYFRAMERESPONSE']._serialized_end=80
  _globals['_POSE']._serialized_start=82
  _globals['_POSE']._serialized_end=137
# @@protoc_insertion_point(module_scope)
